# Generated by Django 4.0 on 2022-10-13 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recognition_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gujrati_files',
            name='image',
            field=models.FileField(upload_to='Uploaded_Data'),
        ),
    ]
